language: node_js
node_js:
- 10.19.0
script:
- node metalsmith.js
deploy:
  detect_encoding: true
  provider: s3
  region: us-west-2
  access_key_id: AKIAIRLY3HXNS5J54CDA
  secret_access_key:
    secure: kO2t1TPsNgFTTJOAyqxMrYw9WkLXw0GM2nvYXzZMH8WyItsi7r8RMkbwgNreffFRUjhhMJi3RUufswD4S6T88TAaxCCVbkiqME7q5c3U+UImLsS3U2j1rnGaEfzV1bTOkeJV78KTqDQ4KryrKLUlG6XMPSJYJOnovtZKbaAagsbqUWHtbkbbgsg0hbfl5kqixu/zlZf09kom4oADkt3I3rnwp4sRmLnNMEB5ARO10eW/iYRbyswq0plg3Kuau1+TLmO6mDgf1xzds2o5lTfEv1t8aGRd/Nx7vKFrRBi4jKFLwrwRpCYc7AKWznh96uc3plxIAqkoAVQNKQRrV1Bigjh5gidneY2ZiXQE5vuFv5miQ/McI9nTLOC3w4BhsWhvxL7Wta2oxW4N0Ox9hmY+24T11FTTVR8G8AbsXTVLHlez4FQId5aBWC7BW4K35wnSXPffHaajAJPq/DofYxsAhF1MSUtW623eLB9xNZdC+qk/Z5gigWzvhjp4d47d4yClcOw7HOnDC3CJYyDz0O2sdya4R9zD6gtySqY3O3ZAqIQRlW/ieOxFROg2Dt0Y3FXS8U2c7y/zWwjesco4RKMe53BEbPQKQWW9xXm0H6lcT9NLdyQTe3nKX5nlGvhNYZINlt9PQ0eRMu363vpZGO7Rc0SQP/3Oi7Am8gk9ooBVJ8A=
  bucket: visualregressiontesting.com
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: visualregressiontesting/visualregressiontesting.com
    branch: master
